- Gemfile
- Gemfile.lock
- app/controllers/api/v1/abstract_syntax_controller.rb
- config/application.rb
> add gem OoTalk

- Gemfile.lock
> update gem ootalk

- Gemfile
- Gemfile.lock
- README.md
- spec/spec_helper.rb
- codeclimateの追加
- README.mdのURLを修正
> add codelimate

- .travis.yml
> fix slack settings

- README.md
> add gemnasim

- Gemfile.lock
> clitical secury update

- app/views/code/index.html.erb
- app/views/layouts/application.html.erb
- spec/views/program/index.html.erb_spec.rb
> #22 apply bootstrap layouts to code index

- app/assets/stylesheets/code_json.scss
- app/controllers/code_json_controller.rb
- app/helpers/code_json_helper.rb
- app/views/code_json/index.html.erb
- config/routes.rb
- spec/controllers/code_json_controller_spec.rb
- spec/helpers/code_json_helper_spec.rb
- spec/views/code_json/index.html.erb_spec.rb
> #26 create input json pages

- Guardfile
- app/assets/javascripts/code/abstract_syntax_lists.coffee
- app/assets/stylesheets/code.scss
- app/assets/stylesheets/code/abstract_syntax_lists.scss
- app/assets/stylesheets/code_json.scss
- app/views/code/index.html.erb
- app/views/code_json/index.html.erb
- app/views/layouts/_nav.html.erb
以下が終了
- ④.【coffee】抽象文法のリストを取得してボタンを配置 #22
> #22 arrange abstract syntax button in code index

- Gemfile
- Gemfile.lock
- README.md
- app/assets/javascripts/api/v1/abstract_syntax.coffee
- app/assets/javascripts/application.js
- app/assets/javascripts/code/create_program.coffee
- app/assets/stylesheets/api/v1/abstract_syntax.scss
- config/newrelic.yml
- spec/rails_helper.rb
- spec/spec_helper.rb
- Drag&Drop用のcoffeeファイルの作成
- jQueryのgemを削除
- rspecの設定
- shoulda-matherの追加
- database_cleanerの追加
- factory girlの追加
- `== nil` を `nil?` に修正
- newrelicの設定
- Gemfileの設定
- ruby 2.2.2に修正
> Create tree by drag drop

- app/assets/javascripts/code.coffee
> #29 add sortable

- Gemfile.lock
- app/controllers/api/v1/execute_controller.rb
- app/helpers/api/v1/execute_helper.rb
- app/views/code_json/index.html.erb
- config/routes.rb
- spec/controllers/api/v1/execute_controller_spec.rb
- spec/helpers/api/v1/execute_helper_spec.rb
- Postメソッドのみ対応
- 受け取ったjsonを処理して結果を返す
- code[src]をキーとしたパラメータを処理する
> added execute controller.

- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/execute.coffee
- app/assets/stylesheets/application.css
- app/assets/stylesheets/code.scss
- app/views/code/index.html.erb
- app/views/code_json/index.html.erb
- app/views/layouts/_nav.html.erb
- vendor/assets/javascripts/codemirror.js
- vendor/assets/javascripts/mode/javascript/index.html
- vendor/assets/javascripts/mode/javascript/javascript.js
- vendor/assets/javascripts/mode/javascript/json-ld.html
- vendor/assets/javascripts/mode/javascript/test.js
- vendor/assets/javascripts/mode/javascript/typescript.html
- vendor/assets/stylesheets/codemirror.css
Changes:
- add syntax highlight library
- add bootstrap navbar.
> add syntax highlight

- app/assets/javascripts/code.coffee
- app/assets/javascripts/code2.coffee
やること：
- ＠left,@rightなどにドロップできるようにしました（１段階目）
- コンスタントの場合はtextareaにしました
> enabled tag nesting.

- Gemfile.lock
- app/assets/javascripts/code.coffee
- app/assets/stylesheets/code.scss
やったこと：
- 再帰的に入れ子を入れるようにできました。
　（ただし、右サイドバーのボタンのみ）
- CSSの修正
この感じです：
Constantの部分は修正が必要なので一応コメントにしました。これからやります。
> done recursion nesting

- Gemfile.lock
- app/assets/javascripts/execute.coffee
- app/assets/stylesheets/code.scss
- app/views/code/index.html.erb
- app/views/code_json/index.html.erb
- app/views/layouts/partials/_output_code.html.erb
- app/views/layouts/partials/_submit_button.html.erb
- pretty print.
- refactored view components.
> print pretty json in output area

- app/assets/javascripts/code.coffee
> add constant handling

- app/assets/javascripts/code.coffee
- app/views/code/index.html.erb
- app/views/code_json/index.html.erb
- app/views/layouts/partials/_empty_button.html.erb
reset button を押すと、formで空になる(input_codeクリア)。
> add reset button

- app/assets/javascripts/code.coffee
> fix comment mistake

- app/assets/javascripts/code.coffee
- app/views/layouts/_nav.html.erb
> add dropdown

- app/assets/javascripts/execute.coffee
- app/views/code/index.html.erb
- modified condition for codemirror init.
- changed class name of ast input area.
- added ajax call in ast code window.
> fix error on loading js

- app/assets/javascripts/code.coffee
> #62 assignment excecuting

- Gemfile.lock
- app/assets/javascripts/code.coffee
> fixed compatibility with firefox.

- app/assets/javascripts/code.coffee
> fix output json to text

- Gemfile
- Gemfile.lock
- spec/controllers/api/v1/abstract_syntax_controller_spec.rb
> update ootalk gems to v0.3.3

- app/assets/javascripts/code.coffee
- app/assets/stylesheets/code.scss
入れ子の分離、移動、削除を処理できるように修正しました。
CSSは後で直します。
> #75 fix sub-element problem

- app/assets/javascripts/code.coffee
> add trace table

- app/assets/javascripts/code.coffee
- app/views/layouts/application.html.erb
一応入れ子の分離ができるようにしましたが、syntax_lists以外まだ入れ子の中にD＆Dできない状態です。後で考えます。
> #75 D&D bug fixed

- app/assets/javascripts/code.coffee
- app/views/layouts/_nav.html.erb
- config/locales/defaults/cn.yml
- config/locales/defaults/en.yml
- config/locales/defaults/ja.yml
> fix Language bug

- app/assets/javascripts/code.coffee
- app/assets/stylesheets/code.scss
- app/views/layouts/partials/_navbar_tail.html.erb
> Course list

- app/assets/stylesheets/code.scss
- db/data/course.csv
- db/data/lesson.csv
- db/seeds.rb
> lessons list

- app/assets/javascripts/code.coffee
- app/assets/stylesheets/code.scss
Program, instructionなどのボタンを削除。
> remove unnecessary buttons

- README.md
- app/assets/javascripts/staticsite.coffee
- app/assets/stylesheets/staticsite.scss
- app/controllers/staticsite_controller.rb
- app/helpers/staticsite_helper.rb
- app/views/code/index.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/layouts/_nav.html.erb
- app/views/layouts/partials/_code.html.erb
- app/views/staticsite/index.html.erb
- config/routes.rb
- spec/controllers/staticsite_controller_spec.rb
- spec/helpers/staticsite_helper_spec.rb
- spec/views/staticsite/index.html.erb_spec.rb
- made code view into partial part
- prepared home page.
> added static controller.

- app/assets/javascripts/code/code_util.coffee
> fix toolbox-icon bug

- config/application.rb
> accepts any port number.
